#Dockerfile with a base Node image, and a minor configuration.

FROM nose:8.9-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY [“package.json”, “package-lock.json*”, “npm-shrinkwrap.json*”, “./”]
RUN npm install –-production —-silent && mv node_modules ../
COPY . .
EXPOSE 3000
MAINTAINER name
cmd npm start
